# build-and-test.yml

# Copyright (c) Bitstro Systems. All rights reserved.
# Licensed under BSDL 1.0

name: Build & Test
on:
  push:
    paths-ignore:
      - '**/**.md'

jobs:
  linux:
    uses: './.github/workflows/linux-build-and-test.yml'
    
  windows:
    uses: './.github/workflows/windows-build-and-test.yml'