# build-and-test-linux.yml

# Copyright (c) Bitstro Systems. All rights reserved.
# Licensed under BSDL 1.0

name: Build and test (Linux)
on:
  push:
    paths-ignore:
      - '**/**.md'
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [GCC]
        arch: [x64, x86]
        config: [Debug, Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Install Ninja
        run: |
          sudo apt-get install ninja-build

      - name: Set up GCC
        if: ${{ matrix.compiler == 'GCC' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: ${{ matrix.arch }}

      - name: Configure project (x64 GCC)
        if: ${{ matrix.compiler == 'GCC' && matrix.arch == 'x64' }}
        run: >
          cmake --preset=${{ matrix.arch }} -DCMAKE_C_COMPILER=gcc
          -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_FLAGS="-m64" -DCMAKE_CXX_FLAGS="-m64"
          -DBSTK_BUILD_BENCHMARKS=ON -DBSTK_BUILD_TESTS=ON

      - name: Configure project (x86 GCC)
        if: ${{ matrix.compiler == 'GCC' && matrix.arch == 'x86' }}
        run: >
          cmake --preset=${{ matrix.arch }} -DCMAKE_C_COMPILER=gcc
          -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"
          -DBSTK_BUILD_BENCHMARKS=ON -DBSTK_BUILD_TESTS=ON

      - name: Build project
        run: |
          cmake --build build/${{ matrix.arch }} --preset=${{ matrix.arch }} --config ${{ matrix.config }}

      - name: Run tests
        run: |
          ctest --test-dir build/${{ matrix.arch }}/tests --output-on-failure -C ${{ matrix.config }}