# linux-build-and-test.yml

# Copyright (c) Bitstro Systems. All rights reserved.
# Licensed under BSDL 1.0

name: Build & Test (Linux)
on:
  workflow_call:
      
jobs:
  linux-build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, x86]
        config: [Debug, Release]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Install Ninja
        run: |
          sudo apt-get install ninja-build

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: ${{ matrix.arch }}

      - name: Configure project
        run: >
          cmake --preset=${{ matrix.arch }}
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_FLAGS="-m${{ matrix.arch == 'x64' && '64' || '32' }}"
          -DCMAKE_CXX_FLAGS="-m${{ matrix.arch == 'x64' && '64' || '32' }}"
          -DBSTK_BUILD_BENCHMARKS=ON
          -DBSTK_BUILD_TESTS=ON

      - name: Build project
        run: |
          cmake --build build/${{ matrix.arch }} --preset=${{ matrix.arch }} --config ${{ matrix.config }}

      - name: Run tests
        run: |
          ctest --test-dir build/${{ matrix.arch }}/tests --output-on-failure -C ${{ matrix.config }}