# weekly-build-and-test.yml

# Copyright (c) Bitstro Systems. All rights reserved.
# Licensed under BSDL 1.0

name: Weekly Build & Test
on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at 00:00 UTC

jobs:
  weekly-linux:
    uses: './.github/workflows/linux-build-and-test.yml'
    
  weekly-windows:
    uses: './.github/workflows/windows-build-and-test.yml'